---
plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - bin/*
    - gemfiles/*

Gemspec/RequireMFA:
  Enabled: false

##########
# LAYOUT #
##########

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

#########
# RSPEC #
#########

RSpec/MultipleExpectations:
  Max: 3

RSpec/NestedGroups:
  Max: 4
